[tool.poetry]
name = "engenharia-dados"
version = "0.1.0"
description = ""
authors = ["victor <victorsoaresferreira09@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
wget = "^3.2"
notebook = "^7.2.1"
<<<<<<< HEAD
pandas = "^2.2.2"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
=======
>>>>>>> f105e1415ea08196551f3e5093c3cb9a2ee485be


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
