CREATE SCHEMA CLUBE_DO_LIVRO;


CREATE TABLE LIVROS (
    ID_LIVRO INT NOT NULL,
    NOME_LIVRO VARCHAR(100) NOT NULL,
    AUTORIA VARCHAR(100) NOT NULL,
    EDITORA VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL,
    PREÇO DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (ID_LIVRO)
)

CREATE TABLE ESTOQUE (
    ID_LIVRO INT NOT NULL,
        QTD_ESTOQUE INT NOT NULL,
    PRIMARY KEY (ID_LIVRO)
)

#Criação das outras tabelas 
CREATE TABLE VENDAS(
    ID_PEDIDO INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    ID_LIVRO INT NOT NULL,
    QTD_VENDIDA INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    PRIMARY KEY (ID_VENDEDOR, ID_PEDIDO)

)

CREATE VENDEDORES(
    ID_VENDEDOR INT NOT NULL,
    NOME_VENDEDOR VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_VENDEDOR)

)

#RELAÇÃO ENTRE LIVROS E ESTOQUE COMMENT
ALTER TABLE ESTOQUE ADD CONSTRAINT CE_LIVROS_ESTQUES
FOREIGH KEY (ID_LIVRO)
REFERENNCES LIVROS (ID_LIVRO)
ON DELETE NO ACTION;
ON UPDATE NO ACTION;

ALTER TABLE VEN